name: "Typst"
on:
  pull_request:
    paths:
      - src/**/*
  push:
    paths:
      - src/**/*
jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: |
            experimental-features = nix-command flakes
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - run: nix develop --command just compile
